
default_storage: main
storages:
  main:
    type: github
    url: git://github.com/shagabutdinov/dotfiles

synchronize:

  - type: storage-git
    name: main
    on_command: pull

  # folders
  - type: file
    path: ~/bin

  - type: file
    path: ~/.config/dunst

  - type: file
    path: ~/.i3

  # files
  - type: file
    path: ~/.config/dotfiles-manager/config.yaml

  - type: file
    path: ~/.Xresources

  - type: file
    path: ~/.gitconfig

  - type: file
    path: ~/.gtkrc-2.0

  - type: file
    path: ~/.gtkrc-2.0.mine

  - type: file
    path: ~/.xinitrc

  - type: file
    path: ~/.vimperatorrc

  - type: file
    path: ~/.zshrc

  # root
  - type: file
    path: /etc/pacman.conf

  # pacman packages
  - type: package-pacman
    packages:
      - infinality-bundle
      - thunar
      - dunst
      - xf86-input-synaptics
      - xorg-xset
      - terminus-font
      - xorg-xmodmap

      - firefox
      - chromium

  # install yaourt
  - type: ruby-script
    script: '::DotfilesManager::PackageYaourt.install'
    on_command: pull

  - type: package-yaourt
    packages:
      - oh-my-zsh-git

  - type: storage-git
    name: main
    on_command: push