#!/usr/bin/env ruby

# based on carcosa-ui
sleep 0.2

*lines, last_line = ARGV[0].split('\n')

lines.each { |line|
  system('xdotool', 'type', '--delay', '2', line)
  system('xdotool', 'key', 'Return')
}

system('xdotool', 'type', '--delay', '2', last_line)
