#!/usr/bin/env ruby
# frozen_string_literal: true

pactl_output = `pactl list sources`
muted = pactl_output.include?('Mute: yes')

sources =
  pactl_output
  .split("\n")
  .select { |line| line.include?('Source #') }
  .map { |line| line.gsub('Source #', '').to_i }
  .each do |sink|
    `pactl set-source-mute #{sink} #{muted ? 0 : 1}`
  end

id = `notify-replace microphone "" "<b>MIC</b> » #{muted ?
  'UNMUTED' : 'MUTED'}"`.strip.to_i

File.write(ID_FILE, id)
