#!/usr/bin/env ruby

require 'securerandom'

text = `xclip -o`.strip()

text.strip().split("\n").each do |line|
  data = [{
    "type": "item_add",
    "temp_id": SecureRandom.uuid,
    "uuid": SecureRandom.uuid,
    "args": {"content": line.strip()}
  }]

  require 'json'
  data = JSON.generate(data)

  require 'shellwords'

  token = File.read(File.expand_path('~/.todoist')).strip

  result =
      `curl \
          --silent \
          -d token=#{token} \
          -d commands=#{Shellwords.escape(data)} \
          "https://todoist.com/API/v6/sync" 2>&1`

  success = result.match(/ok/)
  if success.nil?()
    `notify-send "Failed to create task: #{Shellwords.escape(result)}"`
  else
    `notify-send "Task successfully created"`
  end

  sleep(2)
end
