#!/bin/bash

if [[ $# -lt 2 || "$1" == "-h" ]]; then
  echo usage: "$0 <user> <host>"
  exit 1
fi

# executing root ssh command
ssh $1@$2 "
  # exporting public key
  cd ~;
  mkdir .ssh;
  echo '`cat ~/.ssh/id_rsa.pub`' >> .ssh/authorized_keys;
  chmod og-wrx .ssh -R;

  # exporting correct term to bash profile
  echo 'export TERM=xterm' >> .bash_profile

  if [ \`whoami\` == 'root' ]; then
    # install zsh
    yum -y install zsh wget git vim ruby;
	mkdir ~/bin;
  fi

  export ZSH=~/.oh-my-zsh
  wget --no-check-certificate http://install.ohmyz.sh -O - | sh;
  echo 'export LANG=\"en_US.UTF-8\"' >> ~/.zshrc
  echo 'export PATH=\"\$PATH:~/bin\"' >> ~/.zshrc
  echo 'export TERM=rxvt-unicode' >> ~/.zshrc
  echo 'plugins=(git history-substring-search)' >> ~/.zshrc
  echo 'export PROMPT=\"%{\$bg[magenta]%}%{\$fg[white]%}\`whoami\`@\`hostname\`%{\$reset_color%} %2~: \"' >> ~/.zshrc
"

ssh root@$2 "
  usermod -s /bin/zsh $1;
"
