font:
  normal:
    family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono
    style: Bold

  italic:
    family: Ubuntu Mono
    style: Italic

  bold_italic:
    family: Ubuntu Mono
    style: Bold Italic

  size: 9

selection:
  save_to_clipboard: true

key_bindings:
  - { key: V,   mods: Alt, action: Paste }
  - { key: C,   mods: Alt, action: Copy  }
  - { key: Comma,   mods: Control, chars: "\x1b[23~" }
  - { key: Period,   mods: Control, chars: "\x1b[24~" }

# Colors (Night Owlish Light)
colors:
  bright:
    black: '#7a8181'
    blue: '#5ca7e4'
    cyan: '#00c990'
    green: '#49d0c5'
    magenta: '#697098'
    red: '#f76e6e'
    white: '#989fb1'
    yellow: '#dac26b'
  cursor:
    cursor: '#403f53'
    text: '#fbfbfb'
  normal:
    black: '#011627'
    blue: '#4876d6'
    cyan: '#08916a'
    green: '#2aa298'
    magenta: '#403f53'
    red: '#d3423e'
    white: '#7a8181'
    yellow: '#daaa01'
  primary:
    background: '#ffffff'
    foreground: '#403f53'
  selection:
    background: '#f2f2f2'
    text: '#403f53'

